version: '3.3'
services:
  neo4j:
    image: neo4j
    container_name: neo4j
    restart: always
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - "${NEO4J_DATA}:/data"
    environment:
      - NEO4J_AUTH=neo4j/${PASSWORD}
