---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
    volumes:
      - ~/qbittorrent/config:/config
      - ~/qbittorrent/downloads:/downloads
    ports:
      - 49153:49153
      - 49153:49153/udp
      - 8080:8080
    restart: unless-stopped
