---
version: "2.1"
services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
    volumes:
      - ${QB_CONFIG}:/config
      - ${QB_DATA_PATH}/downloads:/downloads
      - ${QB_DATA_PATH}/watch:/watch
    ports:
      - 49153:49153
      - 49153:49153/udp
      - 8080:8080
