version: "3"

services:
  zfile:
    image: zhaojun1998/zfile:latest
    container_name: zfile
    restart: always
    volumes:
      - ~/zfile/db:/root/.zfile/db
      - ~/zfile/logs:/root/.zfile/logs
      - ~/zfile/storage:/mnt/storage
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zfile.rule=Host(`${SITE:-zfile.docker.localhost}`)"
      - "traefik.http.routers.zfile.service=zfile"
      - "traefik.http.services.zfile.loadbalancer.server.port=8080"

networks:
  default:
    external:
      name: traefik
