version: '3'

services:
  bitwarden:
    image: bitwardenrs/server:latest
    container_name: bitwarden
    expose:
      - "80"
    volumes:
      - bitwarden_data:/data
    environment:
      VIRTUAL_HOST: bw.einvene.info
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: bw.einverne.info
      LETSENCRYPT_EMAIL: admin@einverne.info
    restart: always

volumes:
  bitwarden_data:

networks:
  default:
    external:
      name: nginx-proxy
