version: '3'

services:
  rsshub:
    image: diygod/rsshub
    restart: always
    environment:
      - NODE_ENV=production
      - CACHE_TYPE=redis
      - REDIS_URL=redis://redis:6379/
      - PUPPETEER_WS_ENDPOINT=ws://browserless:3000
      - VIRTUAL_HOST=${YOUR_DOMAIN}
      - VIRTUAL_PORT=1200
      - LETSENCRYPT_HOST=${YOUR_DOMAIN}
      - LETSENCRYPT_EMAIL=${YOUR_EMAIL}
    depends_on:
      - redis
      - browserless

  browserless:
    # See issue 6680
    image: browserless/chrome:1.43-chrome-stable
    restart: always
    ulimits:
      core:
        hard: 0
        soft: 0

  redis:
    image: redis:alpine
    restart: always
    volumes:
        - redis-data:/data

volumes:
  redis-data:

networks:
  default:
    external:
      name: nginx-proxy

