version: "3"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    #network_mode: host
    ports:
      - 1900:1900/udp
      - 3005:3005
      - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    volumes:
      - ${PLEX_CONFIG_PATH}/library:/config
      - ${PATH_TO_TV}:/tv
      - ${PATH_TO_MOVIE}:/movies
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
      - VIRTUAL_HOST=${YOUR_DOMAIN}
      - VIRTUAL_PORT=32400
      - LETSENCRYPT_HOST=${YOUR_DOMAIN}
      - LETSENCRYPT_EMAIL=${YOUR_EMAIL}

networks:
  default:
    external:
      name: nginx-proxy

