version: '3'

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    volumes:
      - ${HOME_PATH}:/srv
        #- ${FB_CONFIG_PATH}/.filebrowser.json:/.filebrowser.json
        #- ${FB_CONFIG_PATH}/database.db:/database.db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="Asia/Shanghai"
      - VIRTUAL_HOST=${YOUR_DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${YOUR_DOMAIN}
      - LETSENCRYPT_EMAIL=${YOUR_EMAIL}

networks:
  default:
    external:
      name: nginx-proxy
