version: '3'

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    volumes:
      - ./data:/srv
      - ./config.json:/config.json
      - ./database.db:/database.db
    environment:
      VIRTUAL_HOST: files.einverne.info
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: files.einverne.info
      LETSENCRYPT_EMAIL: admin@einverne.info

networks:
  default:
    external:
      name: nginx-proxy
