version: '3.3'

services:
  flaresolverr:
    container_name: flaresolverr
    image: 'ghcr.io/flaresolverr/flaresolverr:latest'
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
    ports:
      - '8191:8191'

  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    depends_on:
      - flaresolverr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - AUTO_UPDATE=true
      - RUN_OPTS=${RUN_OPTS}
    volumes:
      - ${CONFIG_PATH}/jackett/config:/config
      - /mnt/video:/downloads
    ports:
      - 9117:9117

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022 #optional
    ports:
      - 7878:7878
    volumes:
      - ${CONFIG_PATH}/radarr/config:/config
      - /mnt/video:/video

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022 #optional
    ports:
      - 8989:8989
    volumes:
      - ${CONFIG_PATH}/sonarr/config:/config
      - /mnt/video:/video

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/readarr/config:/config
      - /mnt/books:/books #optional
      - /mnt/downloadclient-downloads:/downloads #optional
    ports:
      - 8787:8787
