version: '3'

services:
  rss-bridge:
    image: einverne/rss-bridge
    container_name: rss-bridge
    restart: unless-stopped
    volumes:
      - rss-bridge-data:/var/www/html/
    environment:
      VIRTUAL_HOST: rss.einverne.info
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: rss.einverne.info
      LETSENCRYPT_EMAIL: admin@einverne.info

volumes:
  rss-bridge-data:

networks:
  default:
    external:
      name: nginx-proxy