version: '3'

services:
  db:
    image: mysql:5.7
    container_name: chevereto_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: chevereto_root
      MYSQL_DATABASE: chevereto
      MYSQL_USER: chevereto
      MYSQL_PASSWORD: chevereto

  chevereto:
    depends_on:
      - db
    image: einverne/chevereto:latest
    # build: ./
    container_name: chevereto
    restart: always
    environment:
      CHEVERETO_DB_HOST: db:3306
      CHEVERETO_DB_USERNAME: chevereto
      CHEVERETO_DB_PASSWORD: chevereto
      CHEVERETO_DB_NAME: chevereto
      CHEVERETO_DB_PREFIX: chv_
      VIRTUAL_HOST: photo.einverne.info
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: photo.einverne.info
      LETSENCRYPT_EMAIL: admin@einverne.info
    volumes:
      - chevereto:/var/www/html/images

volumes:
  db_data:
  chevereto:

networks:
  default:
    external:
      name: nginx-proxy
