version: "3"
services:
  linx-server:
    image: einverne/linx-server
    container_name: linx-server
    restart: always
    volumes:
      - /var/www/linx/meta:/data/meta
      - /var/www/linx/files:/data/files
    expose:
      - 80
      - 443
    environment:
      VIRTUAL_HOST: linx.einverne.info
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: linx.einverne.info
      LETSENCRYPT_EMAIL: admin@einverne.info

networks:
  default:
    external:
      name: nginx-proxy
