version: "3"
services:
  linx-server:
    image: andreimarcu/linx-server
    container_name: linx-server
    restart: always
    command: -config /data/linx-server.conf
    volumes:
      - ~/linx/meta:/data/meta
      - ~/linx/files:/data/files
      - ./config.conf:/data/linx-server.conf
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
      - VIRTUAL_HOST=linx.einverne.info
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=linx.einverne.info
      - LETSENCRYPT_EMAIL=admin@einverne.info

networks:
  default:
    external:
      name: nginx-proxy
