version: "3"
services:
  nextcloud_db:
    image: mysql:5.7
    container_name: nextcloud_db
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud

  nextcloud:
    image: nextcloud:apache
    container_name: nextcloud_app
    restart: always
    depends_on:
      - nextcloud_db
    expose:
      - 80
      - 443
    volumes:
      - nextcloud:/var/www/html
    environment:
      VIRTUAL_HOST: nc.einverne.info
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: nc.einverne.info
      LETSENCRYPT_EMAIL: admin@einverne.info
volumes:
  db_data:
  nextcloud:
networks:
  default:
    external:
      name: nginx-proxy
