version: '3.3'

services:
  omniedge:
    image: 'omniedge/omniedge:latest'
    restart: always
    logging:
      options:
        max-size: 1g
    network_mode: host
    privileged: true
    environment:
      - OMNIEDGE_SECURITYKEY=${SECURITY_KEY}
      - OMNIEDGE_VIRUTALNETWORK_ID=${NETWORK_ID}
