version: "2.1"

services:
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=${RUN_OPTS}
    volumes:
      - ${CONFIG_PATH}:/config
      - ${DATA_PATH}:/downloads
    ports:
      - 9117:9117
