version: '3.1'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_DB_HOST}
      - PMA_PORT=3306
      - VIRTUAL_HOST=${YOUR_DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${YOUR_DOMAIN}
      - LETSENCRYPT_EMAIL=${YOUR_EMAIL}

networks:
  default:
    external:
      name: nginx-proxy
