version: "3"

services:
  gogs:
    image: gogs/gogs:0.12.9
    container_name: gogs
    restart: always
    volumes:
      - ${GOGS_DATA_PATH}:/data
    ports:
      - "${SSH_PORT}:22"

networks:
  default:
    external: true
    name: nginx-proxy
