version: "3"
services:
  db:
    image: mysql:5.7
    container_name: wordpress_db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    depends_on:
      - db
    volumes:
      - /var/www/html/wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      VIRTUAL_HOST: www.einverne.info
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: www.einverne.info
      LETSENCRYPT_EMAIL: admin@einverne.info
volumes:
    db_data:
networks:
  default:
    external:
      name: nginx-proxy
