version: "3"
services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    volumes:
      - /var/www/html/wordpress/:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: db_host:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      VIRTUAL_HOST: www.einverne.info
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: www.einverne.info
      LETSENCRYPT_EMAIL: admin@einverne.info
networks:
  default:
    external:
      name: nginx-proxy
