version: "3"
services:
  db:
    image: mysql:5.7
    container_name: wordpress_db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${YOUR_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_USER: ${MYSQL_DATABASE_USER}
      MYSQL_PASSWORD: ${MYSQL_DATABASE_PASSWORD}

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    depends_on:
      - db
    volumes:
      - ${WP_CONTENT_PATH}:/var/www/html/wp-content
      - ./upload.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_DATABASE_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      VIRTUAL_HOST: ${YOUR_DOMAIN}
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ${YOUR_DOMAIN}
      LETSENCRYPT_EMAIL: ${YOUR_EMAIL}
volumes:
    db_data:
networks:
  default:
    external:
      name: nginx-proxy
