version: '3'
services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "853:853/tcp"
      - "784:784/udp"
      - "853:853/udp"
      - "8853:8853/udp"
      - "8080:80/tcp"
      - "3000:3000/tcp"
      - "5443:5443/tcp"
      - "5443:5443/udp"
    volumes:
      - ~/adguardhome/work:/opt/adguardhome/work
      - ~/adguardhome/conf:/opt/adguardhome/conf
    environment:
      - TZ=Asia/Shanghai
