version: '3'

services:
  epic:
    image: luminoleon/epicgames-claimer
    container_name: epic
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - AUTO_UPDATE=true
      - EMAIL=${EPIC_EMAIL}
      - PASSWORD=${EPIC_PASSWORD}
    
