version: '3.3'

services:
  alist:
    image: 'xhofe/alist:latest'
    restart: always
    volumes:
      - '${ALIST_CONFIG_PATH}:/opt/alist/data'
    container_name: alist

networks:
  default:
    external: true
    name: nginx-proxy

