version: "3"

services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    restart: always
    volumes:
      - ${PLEX_CONFIG_PATH}:/config
      - ${PATH_TO_MEDIA}:/media:ro
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=Asia/Shanghai
      - PLEX_CLAIM=${PLEX_CLAIM}

