version: "3"
services:
  huginn:
    image: huginn/huginn
    container_name: huginn
    restart: always
    environment:
      HUGINN_DATABASE_ADAPTER: postgresql
      POSTGRES_PORT_5432_TCP_ADDR: ${POSTGRES_DB_ADDR}
      POSTGRES_PORT_5432_TCP_PORT: 5432
      HUGINN_DATABASE_NAME: ${POSTGRES_DATABASE_NAME}
      HUGINN_DATABASE_USERNAME: ${POSTGRES_USERNAME}
      HUGINN_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      VIRTUAL_HOST: ${YOUR_DOMAIN}
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: ${YOUR_DOMAIN}
      LETSENCRYPT_EMAIL: ${YOUR_EMAIL}

networks:
  default:
    external:
      name: nginx-proxy
