version: '3.3'

services:
  freshrss:
    image: linuxserver/freshrss
    container_name: freshrss
    volumes:
      - '~/freshrss:/config'
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - VIRTUAL_HOST=${YOUR_DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${YOUR_DOMAIN}
      - LETSENCRYPT_EMAIL=${YOUR_EMAIL}

networks:
  default:
    external:
      name: nginx-proxy

