version: '3'

services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma
    restart: always
    volumes:
      - ${KUMA_DATA}:/app/data
    environment:
      - TZ=Asia/Shanghai

networks:
  default:
    external: true
    name: nginx-proxy
