version: "3"
services:
  syncthing:
    container_name: syncthing
    image: ghcr.io/linuxserver/syncthing
    hostname: ${HOSTNAME}
    volumes:
      - ~/Syncthing/config:/config
      - ~/SyncthingData:/SyncthingData
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - VIRTUAL_HOST=${YOUR_DOMAIN}
      - VIRTUAL_PORT=8384
      - LETSENCRYPT_HOST=${YOUR_DOMAIN}
      - LETSENCRYPT_EMAIL=${YOUR_EMAIL}

networks:
  default:
    external:
      name: nginx-proxy

